"""
Plain text report generation
Generates simple text format reports from RAG responses
"""

from utils.logger import logging


class TextReportGenerator:
    """Generates plain text reports"""
    
    @staticmethod
    def generate(user_query: str, answer_markdown: str, context: list[str]) -> str:
        """
        Generate a plain text report
        
        Args:
            user_query: User's question/request
            answer_markdown: AI-generated answer (may contain markdown)
            context: List of retrieved context chunks
        
        Returns:
            str: Plain text report content
        """
        logging.info("Generating text report...")
        
        context_text = '\n- '.join(context) if context else 'No sources retrieved'
        
        report = f"""
{'='*70}
ORACLE AWR ANALYSIS REPORT
{'='*70}

QUERY:
{user_query}

{'='*70}

ANALYSIS RESULTS:
{answer_markdown}

{'='*70}

RETRIEVED CONTEXT SOURCES:
- {context_text}

{'='*70}
Generated by Oracle AWR RAG Application
Powered by Advanced AI & Vector Search
{'='*70}
        """
        
        logging.info(f"Text report generated ({len(report)} characters)")
        return report.strip()